### ISSUE TITLE
TODO: Release

### ISSUE THREAD

**Issue by JorVaCoding** [EngineersMods/EngineersWorkshop#1]
- [x] Recipes 
- [x] Balance and tune number
  - [x] Finish config
- [x] Look for bugs / fix em
    - [x] Fix lag when table is placed (Freezes the client for a few ticks)
- [x] Make it read 8,000 instead of 8 000 in WAILA GUI
- [x] Remove unused code
   - [x] Clean Up
- [x] Check that all upgrades work
   - [x] Fix export / import
      - [x] Made textures render in transfer GUI
    - [x] Fix Solar panel upgrade saying its Night-time all the time even when daytime
      - [x] Make solar panel upgrade stack
- [x] Make texture for fuel upgrade thing (@EwyBoy)
- [ ] Shift + break should store the content of the block (No silk touch)
